[project]
name = "vscode-dvc-demo"
version = "0.1.0"
description = "Demo project used for developing VSCode extension"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dvc[s3]==3.66.1",
    "torch==2.10.0",
    "torchvision==0.25.0",
    "dvclive==3.49.0",
]
